# Generated by Django 3.0.2 on 2020-12-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='on_off_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='rgb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.IntegerField()),
                ('g', models.IntegerField()),
                ('b', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Termometr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField()),
                ('temp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='trm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izm1', models.IntegerField()),
                ('izm2', models.IntegerField()),
                ('izm3', models.IntegerField()),
                ('izm4', models.IntegerField()),
                ('izm5', models.IntegerField()),
            ],
        ),
    ]
