# Generated by Django 3.0.2 on 2020-12-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Led',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.TextField()),
                ('number', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LedName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_name', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='rgb',
        ),
        migrations.DeleteModel(
            name='trm',
        ),
    ]
