# Generated by Django 3.1.4 on 2020-12-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_control', '0002_auto_20201215_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='on_off_position',
            new_name='PosTerm',
        ),
        migrations.RenameField(
            model_name='posterm',
            old_name='position',
            new_name='pos_term',
        ),
    ]
