# Generated by Django 3.1.4 on 2020-12-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_control', '0003_auto_20201226_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rgb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.IntegerField()),
                ('g', models.IntegerField()),
                ('b', models.IntegerField()),
            ],
        ),
    ]
