# Generated by Django 3.1.4 on 2020-12-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_control', '0005_auto_20201226_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rgb',
            old_name='B',
            new_name='b',
        ),
        migrations.RenameField(
            model_name='rgb',
            old_name='G',
            new_name='g',
        ),
        migrations.RenameField(
            model_name='rgb',
            old_name='R',
            new_name='r',
        ),
    ]
